Repository NFT-D/Eat-With-Me, pull requests merged in 2022-04, with the labels that each got.

#25 Preliminary Backend
  App.tsx
  package-lock.json
  package.json
  screens/HostMealScreen.tsx
  services/firebase.ts
Labels: Milestone 3, Backend

#24 connected frontend to backend
  App.tsx
  package-lock.json
  package.json
  screens/HostMealScreen.tsx
  screens/ViewMealScreen.tsx
  services/firebase.ts
Labels: Milestone 3, Frontend/UI, Backend

#37 32 update readmemd
  README.md
Labels: documentation, Milestone 3

#42 Home screen
  App.tsx
  components/Confirmation.tsx
  components/MyButton.tsx
  package-lock.json
  package.json
  screens/HomeScreen.tsx
  screens/HostMealScreen.tsx
  screens/LogInScreen.tsx
  screens/SignUpScreen.tsx
  screens/StartUpScreen.tsx
  screens/ViewMealScreen.tsx
  services/firebase.ts
Labels: Milestone 4, Frontend/UI, Backend

#45 My mealscreen
  App.tsx
  components/MyField.tsx
  screens/HomeScreen.tsx
  screens/HostMealScreen.tsx
  screens/LogInScreen.tsx
  screens/MyMealScreen.tsx
  screens/MyProfileScreen.tsx
  screens/SignUpScreen.tsx
  screens/StartUpScreen.tsx
  screens/ViewMealScreen.tsx
  services/firebase.ts
Labels: Milestone 4, Host Functionality, Guest Functionality, Frontend/UI, Backend

#49 Uiimprovements
  App.tsx
  app.config.js
  components/MyButton.tsx
  components/MyField.tsx
  package-lock.json
  package.json
  screens/HomeScreen.tsx
  screens/HostMealScreen.tsx
  screens/LogInScreen.tsx
  screens/MyMealScreen.tsx
  screens/SignUpScreen.tsx
  screens/StartUpScreen.tsx
  screens/ViewMealScreen.tsx
  services/firebase.ts
Labels: Milestone 4, Frontend/UI, Backend

#50 31 cloud storage for photos
  assets/pizza.png
  helpers/upload-image.ts
  package-lock.json
  package.json
  screens/HomeScreen.tsx
  screens/HostMealScreen.tsx
  screens/MyMealScreen.tsx
  screens/MyProfileScreen.tsx
  screens/SignUpScreen.tsx
  screens/ViewMealScreen.tsx
  services/firebase.ts
Labels: Milestone 4, Backend
